"""Facade for report probe helpers, split into focused submodules.

Kept for backward compatibility: existing code and tests import these
names from forensia.report.probes.
"""

# backward-compat aliases — legacy callers import these from forensia.report.probes
from forensia.knowledge import (  # noqa: E402
    catalog_artifact_names,
    catalog_exe_globs,
    catalog_names,
    catalog_path_terms,
    exe_glob_sql,
    matches_exe_globs,
)
from forensia.report.markdown import (  # noqa: F401
    _build_host_note,
    _markdown_table,
    _render_json_table_blocks,
    _render_timestamp_with_timezone,
    _sort_markdown_table_by_first_column,
    _strip_hidden_report_columns_from_markdown_tables,
    _tz_offset_str,
    render_rows_template,
)
from forensia.report.report_brief import (  # noqa: F401
    _EVIDENCE_PATH_KEYS,
    _annotate_confirmed_hypotheses,
    _build_report_brief,
    _dedupe_claims,
    _has_benign_context_tag,
    _hypothesis_source_rule_ids,
    _is_local_machine_account_4648,
    _query_evtx_time_range,
    _query_existing_claims,
    _query_hypotheses_by_status,
    _query_prior_sections,
    _query_top_findings,
    _rule_ids_have_benign_context,
    _sanitize_evidence_paths,
    _short_path_context,
    _summarize_section_coverage,
    write_report_brief,
)
from forensia.report.section_quality import (  # noqa: F401
    BLOCK_HINT_PATTERN,
    GAP_PATTERN,
    QUESTION_HINT_PATTERN,
    RAW_EVIDENCE_HEADING_PATTERN,
    TemplateMeta,
    _collect_event_ids_from_results,
    _collect_section_coverage,
    _correlation_finding_ids,
    _coverage_source_label,
    _coverage_table_markdown,
    _duplicate_finding_titles,
    _ensure_appendix_interpretations,
    _event_claim_gaps,
    _final_report_section_body,
    _load_event_id_hints,
    _load_template_meta,
    _parse_markdown_answer_rows,
    _parse_section_run_payload,
    _refresh_appendix_structured_blocks,
    _sanitize_raw_evidence_body,
    _section_confidence,
    _strip_narrative_status_lines,
    _title_from_template_body,
    _validate_body_evidence_ids,
    _verify_block_output,
    collect_gaps,
)
from forensia.report.section_store import (  # noqa: F401
    _SCAFFOLD_PATTERNS,
    _claim_support_status,
    _claim_text_key,
    _collect_claim_provenance,
    _dump_section_evidence_json,
    _dump_section_questions_json,
    _dump_section_trace_json,
    _extract_claim_texts,
    _update_section_quality_only,
    _upsert_claims,
    _upsert_report_section,
    fetch_report_sections,
    load_report_sections_map,
    mark_report_sections_ai_exhausted,
    set_report_section_status,
)
from forensia.report.summary_tables import (  # noqa: F401
    _FINDING_THEME_FILTER_SQL,
    _TABLE_BLOCK_BUILDERS,
    _TABLE_COLUMNS,
    _account_summary_rows,
    _antiforensic_rows,
    _as_int,
    _build_accounts_table,
    _build_antiforensic_table,
    _build_evidence_gaps_table,
    _build_evidence_scope_table,
    _build_execution_table,
    _build_file_artifacts_table,
    _build_gaps_confirmed_table,
    _build_gaps_unresolved_table,
    _build_gaps_untestable_table,
    _build_key_findings_table,
    _build_network_table,
    _build_recommendations_table,
    _build_systems_observed_table,
    _build_timeline_chronological_table,
    _build_timeline_phase_table,
    _collect_flat_evidence_rows,
    _count_findings_with_tag,
    _count_table,
    _event_interpretation,
    _execution_rows,
    _file_artifact_rows,
    _finding_theme,
    _finding_theme_counts,
    _finding_theme_rank,
    _finding_theme_recommended_action,
    _finding_theme_summary,
    _finding_theme_title,
    _first_nonempty,
    _forensic_gap_rows,
    _has_antiforensic_executions,
    _host_summary_rows,
    _hypothesis_count,
    _hypothesis_rows,
    _load_finding_theme_specs,
    _load_table_captions,
    _max_severity,
    _network_summary_rows,
    _phase_interpretation,
    _row_to_summary_line,
    _sample_labels,
    _section_gap_rows,
    _sentence_list,
    _severity_rank,
    _signal_executable_labels,
    _signal_finding_rows,
    _summarize_flat_evidence_rows,
    _table_block_columns,
    _timeline_phase_rows,
    _timeline_rows,
    render_table_block,
)

_catalog_exe_globs = catalog_exe_globs
_catalog_names = catalog_names
_catalog_path_terms = catalog_path_terms
_catalog_artifact_names = catalog_artifact_names
_exe_glob_sql = exe_glob_sql
_matches_exe_globs = matches_exe_globs
