"""Facade for LLM prompt builders, split into focused submodules.

Kept for backward compatibility: existing code and tests import these
names from forensia.ai.prompts.
"""

from forensia.ai.prompt_context import (  # noqa: F401
    _RULE_INSTANCE_SUFFIX,
    _SQL_COOKBOOK,
    _assemble_messages_with_budget,
    _build_event_id_guidance,
    _build_schema_guidance,
    _case_profile_guidance,
    _collect_event_ids,
    _collect_source_verdicts,
    _enforce_system_budget,
    _estimate_message_tokens,
    _format_evidence_coverage,
    _format_evidence_row,
    _format_schema_card,
    _lang_instruction,
    _load_event_id_hints,
    _load_schema_hints,
    _output_language,
    _rows_to_markdown_table,
    _rule_pattern,
    _slim_brief_items,
    _slim_findings,
    _slim_history,
    _slim_hypothesis_dump,
    _slim_report_brief_for_section,
    _summarize_context_sections,
    _time_range_guidance,
    _trim_dynamic_content,
    _truncate_context_sections,
)
from forensia.ai.prompt_investigation import (  # noqa: F401
    _load_benign_context_rules,
    _render_prior_attempts,
    build_finding_extractor_messages,
    build_gap_identifier_messages,
    build_hypothesis_drafter_messages,
    build_memory_updater_messages,
    build_query_intent_messages,
    build_sql_composer_messages,
    build_sql_self_check_messages,
    build_verdict_review_messages,
)
from forensia.ai.prompt_playbook import (  # noqa: F401
    _CATALOG_ENTITY_COLUMNS,
    _PLAYBOOK_SECTION_DROP_ORDER,
    _SECTION_KEY_MAP,
    RuleContext,
    _auth_event_ids,
    _dfir_playbook,
    _format_artifact_inference,
    _get_cached_rules,
    _load_dfir_yamls,
    _load_question_routing_raw,
    _load_schema_notes,
    _render_app_catalog_narrative,
    _render_artifact_inference_narrative,
    _render_event_narrative,
    _render_extractor_narrative,
    _render_fp_narrative,
    _render_ioc_catalog_narrative,
    _render_logon_narrative,
    _render_priority_narrative,
    _render_schema_narrative,
    _sections_for_hypothesis,
    resolve_rule_context,
)
from forensia.ai.prompt_sections import (  # noqa: F401
    SECTION_REVIEW_SCHEMA,
    _filter_prior_runs_by_heading,
    _format_outline,
    _section_context_block,
    _section_coverage_block,
    _section_evidence_block,
    _section_verification_block,
    build_benchmark_classify_messages,
    build_paragraph_narrate_messages,
    build_report_section_messages,
    build_section_agent_check_messages,
    build_section_agent_plan_messages,
    build_section_outline_messages,
    build_section_review_messages,
    build_structured_classify_messages,
)
